export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const ADD_FLASH_LOADING = 'ADD_FLASH_LOADING';
export const DELETE_FLASH_LOADING = 'DELETE_FLASH_LOADING';
